# This is a basic workflow to help you get started with Actions 

name: Release

# Controls when the workflow will run
on:
  push:
    branches:
      - test/continous-deployment
  release:
    types:
      - created
      
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # or: 'beta' or 'master'
    - working-directory: ./frontend/marketplace
      run: flutter --version
    - working-directory: ./frontend/marketplace
      run: flutter pub get
    #- run: flutter test
    - working-directory: ./frontend/marketplace
      run: flutter build web
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_ACCESS_KEY_SECRET}}
        aws-region: us-east-1
        
    - name: Sync to S3
      run: aws s3 sync . s3://marketplace-s3bucket --delete --cache-control maxage=0 --acl public-read
      working-directory: ./frontend/marketplace/build/web
